# Generated by Django 5.0.6 on 2024-06-03 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_friendrequest_accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
